[UPD] | update function |

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -3,63 +3,170 @@ name: chocolatine
 on:
   push:
     branches-ignore:
-      - 'ga-ignore-*'
+    - "ga-ignore-*"
   pull_request:
+    branches-ignore:
+    - "ga-ignore-*"
 
 env:
-  MIRROR_URL: 'git@github.com:BryanBole/Chocolatine.git'
-  EXECUTABLES: 'mysh'
+  MIRROR_URL: "git@github.com:Remi-Mergen/chocolatine-mirror.git"
+  EXECUTABLES: "binary"
+  ARGUMENTS: ""
 
 jobs:
   check_coding_style:
+    name: "Use coding_style_checker script to verify if the code is clean and report any coding-style errors"
     runs-on: ubuntu-latest
-    container:
-      image: ghcr.io/epitech/coding-style-checker:latest
+    container: ghcr.io/epitech/coding-style-checker:latest
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-      - name: Run coding style checker
-        run: check.sh $(pwd) $(pwd)
-  check_program_compilation:
-    runs-on: ubuntu-latest
-    needs: "check_coding_style"
-    container:
-      image: epitechcontent/epitest-docker
-    timeout-minutes: 2
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-      - name: Build code
+      - uses: actions/checkout@v3
+      - id: check_coding_style
         run: |
-          make
-      - name: Build code 1
-        run: |
-          make clean
-      - name: Verify executables
-        run: |
-          for exe in $(echo "${{ env.EXECUTABLES }}"); do
-            test -x $exe || exit 1
+          CODING_STYLE_ERRORS=$(check.sh $(pwd) $(pwd))
+          for ERRORS in $CODING_STYLE_ERRORS; do
+            array=(`echo $ERRORS | sed 's/:/\n/g'`)
+            echo "::error file=${array[1]#./},title=${array[3]#./} coding style errors detected: ${array[2]#./}::${array[4]#./}"
           done
-  run_tests:
+          if [[ -n $CODING_STYLE_ERRORS ]]
+          then
+            exit 1
+          else
+            echo No coding style errors detected
+          fi
+  
+
+  check_repo:
+    name: "Checks if the repository is clean and void of any unwanted files (temp files, binary files, etc.)"
     runs-on: ubuntu-latest
-    needs: "check_program_compilation"
+    steps:
+      - uses: actions/checkout@v3
+      - id: check_repo
+        run: |
+          UNWANTED_FILES=$(find . -type f -not -path "./git/*" -wholename "*tmp/*" -or -name "*~" -or -name "*.o" -or -name "*.so" -or -name "*.gcno" -or -name "*.gcda" -or -name "*#" -or -name "#*" -or -name "*.gcov" -or -name "*pain_au_chocolat*")
+          for FILES in $UNWANTED_FILES; do
+            echo "::error file=${FILES#./},title=Unwanted file detected::${FILES#./}"
+          done
+          if [[ -n $UNWANTED_FILES ]]
+          then
+            exit 1
+          else
+            echo No unwanted files detected
+          fi
+
+  check_program_compilation:
+    needs: [check_repo]
+    name: "Checks if make compil and test all binary listed in the ARGUMENTS variable"
+    runs-on: ubuntu-latest
     container:
-      image: epitechcontent/epitest-docker
-    timeout-minutes: 2
+      image: epitechcontent/epitest-docker:latest
+
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-      - name: Run tests
-        run: make tests_run
-  push_to_mirror:
+      - uses: actions/checkout@v3
+      - id: check_program_compilation
+        run: make
+        timeout-minutes: 2
+      - run: make clean
+      - run: |
+          OIFS=$IFS
+          IFS=','
+          for x in $EXECUTABLES
+            do
+              ./$x $ARGUMENTS
+            done
+          IFS=$OIFS
+
+  run_tests:
+    needs: [check_program_compilation]
+    name: "Runs tests with criterion"
     runs-on: ubuntu-latest
-    needs: "run_tests"
-    if: github.event_name == 'push'
+    container:
+      image: epitechcontent/epitest-docker:latest
+
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-      - name: Push to mirror repository
-        uses: pixta-dev/repository-mirroring-action@v1
+      - uses: actions/checkout@v3
+      - id: run_tests
+        run: make tests_run
+        timeout-minutes: 2
+
+  push_to_mirror:
+    needs: [run_tests]
+    if: ${{ github.event_name == 'push' }}
+    name: "Push all files to mirror specified"
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v2
         with:
-          mirror_url: ${{ env.MIRROR_URL }}
-          git_ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
+          fetch-depth: 0
+      - uses: pixta-dev/repository-mirroring-action@v1
+        with:
+          target_repo_url:
+            ${{ env.MIRROR_URL }}
+          ssh_private_key:
+            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
+
+# name: chocolatine
+
+# on:
+#   push:
+#     branches-ignore:
+#       - 'ga-ignore-*'
+#   pull_request:
+
+# env:
+#   MIRROR_URL: 'git@github.com:BryanBole/Chocolatine.git'
+#   EXECUTABLES: 'mysh'
+
+# jobs:
+#   check_coding_style:
+#     runs-on: ubuntu-latest
+#     container:
+#       image: ghcr.io/epitech/coding-style-checker:latest
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v2
+#       - name: Run coding style checker
+#         run: check.sh $(pwd) $(pwd)
+#   check_program_compilation:
+#     runs-on: ubuntu-latest
+#     needs: "check_coding_style"
+#     container:
+#       image: epitechcontent/epitest-docker
+#     timeout-minutes: 2
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v3
+#       - name: Build code
+#         run: |
+#           make
+#       - name: Build code 1
+#         run: |
+#           make clean
+#       - name: Verify executables
+#         run: |
+#           for exe in $(echo "${{ env.EXECUTABLES }}"); do
+#             test -x $exe || exit 1
+#           done
+#   run_tests:
+#     runs-on: ubuntu-latest
+#     needs: "check_program_compilation"
+#     container:
+#       image: epitechcontent/epitest-docker
+#     timeout-minutes: 2
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v2
+#       - name: Run tests
+#         run: make tests_run
+#   push_to_mirror:
+#     runs-on: ubuntu-latest
+#     needs: "run_tests"
+#     if: github.event_name == 'push'
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v2
+#       - name: Push to mirror repository
+#         uses: pixta-dev/repository-mirroring-action@v1
+#         with:
+#           mirror_url: ${{ env.MIRROR_URL }}
+#           git_ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
