[UPD] | update function |

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -14,12 +14,22 @@ jobs:
   check_coding_style:
     runs-on: ubuntu-latest
     container:
-      image: ghcr.io/epitech/coding-style-checker:latest
+      image: epitechcontent/epitest-docker:latest
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-      - name: Run coding style checker
-        run: check.sh $(pwd) $(pwd)
+      - uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+      - run: |
+          UNWANTED_FILES=$(find . -type f -not -path "./git/*" -wholename "*tmp/*" -or -name "*~" -or -name "*.o" -or -name "*.so" -or -name "*.gcno" -or -name "*.gdca" -or -name "*.gcov" -or -name "*pain_au_chocolat*")
+          for FILES in $UNWANTED_FILES; do
+            echo "::error file=${FILE#./}, title=Unwanted file detected::${FILE#./}"
+          done
+          if [[ -n $UNWANTED_FILES ]]
+          then
+            exit 1
+          else
+            echo No unwanted files detected
+          fi
   check_program_compilation:
     needs:
       - check_coding_style
